### ISSUE TITLE
arduino mini pro specification

### ISSUE THREAD

**Issue by Benoit3535** [vizual54/APM-Mavlink-to-FrSky#5]
Hello,

I have checked that the APM sends telemetry using a 3DR telemetry module.
I am trying to use your code on an arduino mini pro to get telemetry on a frsky D8R-XP.
In the arduino IDE, the card type is "arduino mini pro 5V 16Mhz (atmega328)"
I have plugged the arduino this way
APM telemetry red -> arduino VCC
APM telemetry black -> arduino GND
APM telemetry yellow (I also tried the green wire) -> arduino RXD

I have activated the DEBUG traces. It seems that no data is received by the arduino (variable "Serial").
I see "Making rate request" and APM data all set to 0.
The arduino mini pro type does it matter  (5V, 3.3V, 8Mzh, 16Mhz...) ?
How can I receive data from the APM, or be sure data is actualy sent ?
Thanks for you job and for your help

Benoit

**Comment by Benoit3535** [comment]
I have plugged the "APM telemetry yellow" to "Arduino RXD on the side way". This time the traces contain values. I will retry with a frsky receiver.

**Comment by vizual54** [comment]
Hi!
Sorry I missed this issue in my mail. Seems like you got it working.
