### ISSUE TITLE
Arduino 1.6.4 hangs compiling 

### ISSUE THREAD

**Issue by PA0MHE** [vizual54/APM-Mavlink-to-FrSky#8]
When compiling APM-Mavlink-to-FrSky Arduino "hangs' without a error message, this is what I see:

_Build options changed, rebuilding all
Using library SoftwareSerial in folder: D:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial 
Using library flexitimer2 in folder: D:\Users\Maarten\Documents\Arduino\libraries\flexitimer2 (legacy)
Using library FastSerial in folder: D:\Users\Maarten\Documents\Arduino\libraries\FastSerial (legacy)
Using library GCS_MAVLink in folder: D:\Users\Maarten\Documents\Arduino\libraries\GCS_MAVLink (legacy)

D:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10604 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR -ID:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino -ID:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\eightanaloginputs -ID:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial -ID:\Users\Maarten\Documents\Arduino\libraries\flexitimer2 -ID:\Users\Maarten\Documents\Arduino\libraries\FastSerial -ID:\Users\Maarten\Documents\Arduino\libraries\GCS_MAVLink C:\Users\Maarten\AppData\Local\Temp\build7870361448349789686.tmp\APM_Mavlink_to_FrSky.cpp -o C:\Users\Maarten\AppData\Local\Temp\build7870361448349789686.tmp\APM_Mavlink_to_FrSky.cpp.o_ 

I really hope to get this working, and would be very thankfull for support, Maarten

**Comment by vizual54** [comment]
Take a look at this fork https://github.com/t413/APM-Mavlink-to-FrSky

**Comment by PA0MHE** [comment]
my error
